### PR TITLE
 Remove refresh from user create

### PR DESCRIPTION
**Pull request by wwjbatista**
Ref.  killbill/killbill-admin-ui#166

### CODE REVIEW

**Comment by pierre** [comment]
Why this change?

**Comment by wwjbatista** [comment]
@pierre,  the refresh throws a 404, but the data is saved in killbill. This error causes that the data not to be saved into kaui. Maybe is my environment. I was thinking caching the error, but for me that do not make any sense. I tested again and the same problem still occurs. If I put some breakpoints in killbill (debug mode) its works, maybe is some performance issue in my environment.

**Comment by pierre** [comment]
@wwjbatista I'm really confused because the creation should be synchronous, so the data should be persisted as soon as the `create` call returns. It would be worth getting to the bottom of this.

Maybe try to put a breakpoint in the DAO to understand if the 404 comes from the new code and if so, why?

**Comment by wwjbatista** [comment]
@pierre, the problem was on the url encoding (https://github.com/killbill/killbill-client-ruby/blob/c0071f72fc100ea59b9d01c95bd799e11ac03e02/lib/killbill_client/api/net_http_adapter.rb#L81)

When creating a user `Joe Doe` the server will set a location as this `http://127.0.0.1:8080/1.0/kb/security/users/Joe%20Doe/roles`; the refresh will made a call after the encoding as this `http://127.0.0.1:8080/1.0/kb/security/users/Joe%2520Doe/roles` making the username `Joe%20Doe` and then the 404 comes to appear.

I reversed the previous commit, and pushed a new one that include a url decode before the call.

**Pull request merged**
