### PR TITLE
Migrate to RSpec 3.4

### PR DESCRIPTION
**Pull request by bolshakov**
I upgraded RSpec to latest stable version. Hope it will be useful

### CODE REVIEW

**Comment by bolshakov** [comment]
I disabled build on ruby 1.8.7 and 1.9.2 since [they are not supported since 2014](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/)

**Comment by pierre** [comment]
Unfortunately, we have many enterprise users still on Ruby 1.8.7 :crying_cat_face: 

Does RSpec 3.4 still support legacy Ruby versions?

**Comment by bolshakov** [comment]
Yes, it does. But I had strange failures when trying to install rake on legacy rubies https://travis-ci.org/killbill/killbill-client-ruby/builds/116362279

**Comment by pierre** [comment]
Can you try constraining the Rake version?

```
s.add_development_dependency 'rake', '>= 10.0.0', '< 11.0.0'
```

See also the discussion here: https://github.com/killbill/killbill-paypal-express-plugin/pull/7.

**Comment by bolshakov** [comment]
@pierre done! I also rebased on master, so it will fix build on master too

**Comment by pierre** [comment]
Thanks! :tada: 

FYI, I've pushed 259127e990cadd1889a8cae2f9c746eb02105b69 to fix a deprecation message.

**Pull request merged**
